version: "3.9"

services:
  bot:
    build: .
    command: ["python", "-m", "bot.bot"]
    restart: unless-stopped
    volumes:
      - .:/app

  scraper:
    build: .
    entrypoint: ["/entrypoint.sh"]
    restart: unless-stopped
    volumes:
      - .:/app

